// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9KrGTBj-2QuF8uQi_kwM88XCFXW7aJw',
    appId: '1:964026866873:web:d709dc0ef5c869954a8f68',
    messagingSenderId: '964026866873',
    projectId: 'innowah-f271c',
    authDomain: 'innowah-f271c.firebaseapp.com',
    storageBucket: 'innowah-f271c.appspot.com',
    measurementId: 'G-E927KFRKJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqUbqjwYFokT2eEVEdM4N7Ucdw7jDFs44',
    appId: '1:964026866873:android:0aa32acb04577eb94a8f68',
    messagingSenderId: '964026866873',
    projectId: 'innowah-f271c',
    storageBucket: 'innowah-f271c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxvcBMuGo9UkEcnuUZGnfr3pO73l-iiaQ',
    appId: '1:964026866873:ios:ef893df7c323e4b64a8f68',
    messagingSenderId: '964026866873',
    projectId: 'innowah-f271c',
    storageBucket: 'innowah-f271c.appspot.com',
    iosBundleId: 'com.example.renewealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxvcBMuGo9UkEcnuUZGnfr3pO73l-iiaQ',
    appId: '1:964026866873:ios:ac69366d878969554a8f68',
    messagingSenderId: '964026866873',
    projectId: 'innowah-f271c',
    storageBucket: 'innowah-f271c.appspot.com',
    iosBundleId: 'com.example.renewealth.RunnerTests',
  );
}
